run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    # Essential linters
    - govet
    - staticcheck
    - typecheck
    - unused
    - ineffassign
    
    # Code quality (less strict)
    - gosimple
    - bodyclose
    - noctx

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - errcheck

    # Allow fmt.Errorf without wrapping
    - text: "non-wrapping format verb for fmt.Errorf"
      linters:
        - errorlint

  max-issues-per-linter: 50
  max-same-issues: 10
