version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - bodyclose
    - govet
    - ineffassign
    - noctx
    - staticcheck
    - unused
  settings:
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
          - noctx
        path: _test\.go
      - linters:
          - errorlint
        text: non-wrapping format verb for fmt.Errorf
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
