// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: internal/cluster/proto/node.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PingRequest is an empty request for health checking.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_cluster_proto_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_node_proto_rawDescGZIP(), []int{0}
}

// PingResponse contains node status information.
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`     // "hot", "warm", "cold"
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "healthy", "degraded", "unhealthy"
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	StorageStats  *StorageStats          `protobuf:"bytes,5,opt,name=storage_stats,json=storageStats,proto3" json:"storage_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_cluster_proto_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_node_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PingResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PingResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *PingResponse) GetStorageStats() *StorageStats {
	if x != nil {
		return x.StorageStats
	}
	return nil
}

// StorageStats contains storage utilization information.
type StorageStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalBytes    int64                  `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	UsedBytes     int64                  `protobuf:"varint,2,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	FreeBytes     int64                  `protobuf:"varint,3,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	BlobCount     int64                  `protobuf:"varint,4,opt,name=blob_count,json=blobCount,proto3" json:"blob_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageStats) Reset() {
	*x = StorageStats{}
	mi := &file_internal_cluster_proto_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageStats) ProtoMessage() {}

func (x *StorageStats) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageStats.ProtoReflect.Descriptor instead.
func (*StorageStats) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_node_proto_rawDescGZIP(), []int{2}
}

func (x *StorageStats) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *StorageStats) GetUsedBytes() int64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *StorageStats) GetFreeBytes() int64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *StorageStats) GetBlobCount() int64 {
	if x != nil {
		return x.BlobCount
	}
	return 0
}

// TransferBlobRequest is streamed to transfer blob data.
type TransferBlobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First message contains metadata, subsequent messages contain data chunks.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*TransferBlobRequest_Metadata
	//	*TransferBlobRequest_DataChunk
	Payload       isTransferBlobRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferBlobRequest) Reset() {
	*x = TransferBlobRequest{}
	mi := &file_internal_cluster_proto_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferBlobRequest) ProtoMessage() {}

func (x *TransferBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferBlobRequest.ProtoReflect.Descriptor instead.
func (*TransferBlobRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_node_proto_rawDescGZIP(), []int{3}
}

func (x *TransferBlobRequest) GetPayload() isTransferBlobRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TransferBlobRequest) GetMetadata() *BlobMetadata {
	if x != nil {
		if x, ok := x.Payload.(*TransferBlobRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *TransferBlobRequest) GetDataChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*TransferBlobRequest_DataChunk); ok {
			return x.DataChunk
		}
	}
	return nil
}

type isTransferBlobRequest_Payload interface {
	isTransferBlobRequest_Payload()
}

type TransferBlobRequest_Metadata struct {
	Metadata *BlobMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type TransferBlobRequest_DataChunk struct {
	DataChunk []byte `protobuf:"bytes,2,opt,name=data_chunk,json=dataChunk,proto3,oneof"`
}

func (*TransferBlobRequest_Metadata) isTransferBlobRequest_Payload() {}

func (*TransferBlobRequest_DataChunk) isTransferBlobRequest_Payload() {}

// BlobMetadata contains information about a blob being transferred.
type BlobMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ContentHash      string                 `protobuf:"bytes,1,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Size             int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	IsEncrypted      bool                   `protobuf:"varint,3,opt,name=is_encrypted,json=isEncrypted,proto3" json:"is_encrypted,omitempty"`
	EncryptionScheme string                 `protobuf:"bytes,4,opt,name=encryption_scheme,json=encryptionScheme,proto3" json:"encryption_scheme,omitempty"`
	EncryptionIv     string                 `protobuf:"bytes,5,opt,name=encryption_iv,json=encryptionIv,proto3" json:"encryption_iv,omitempty"`
	BlobType         string                 `protobuf:"bytes,6,opt,name=blob_type,json=blobType,proto3" json:"blob_type,omitempty"` // "single", "composite", "delta"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BlobMetadata) Reset() {
	*x = BlobMetadata{}
	mi := &file_internal_cluster_proto_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobMetadata) ProtoMessage() {}

func (x *BlobMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobMetadata.ProtoReflect.Descriptor instead.
func (*BlobMetadata) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_node_proto_rawDescGZIP(), []int{4}
}

func (x *BlobMetadata) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *BlobMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BlobMetadata) GetIsEncrypted() bool {
	if x != nil {
		return x.IsEncrypted
	}
	return false
}

func (x *BlobMetadata) GetEncryptionScheme() string {
	if x != nil {
		return x.EncryptionScheme
	}
	return ""
}

func (x *BlobMetadata) GetEncryptionIv() string {
	if x != nil {
		return x.EncryptionIv
	}
	return ""
}

func (x *BlobMetadata) GetBlobType() string {
	if x != nil {
		return x.BlobType
	}
	return ""
}

// TransferBlobResponse indicates the result of a blob transfer.
type TransferBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ContentHash   string                 `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferBlobResponse) Reset() {
	*x = TransferBlobResponse{}
	mi := &file_internal_cluster_proto_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferBlobResponse) ProtoMessage() {}

func (x *TransferBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferBlobResponse.ProtoReflect.Descriptor instead.
func (*TransferBlobResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_node_proto_rawDescGZIP(), []int{5}
}

func (x *TransferBlobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferBlobResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TransferBlobResponse) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

// RetrieveBlobRequest requests a blob by its content hash.
type RetrieveBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentHash   string                 `protobuf:"bytes,1,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // Optional: for range requests
	Length        int64                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"` // Optional: for range requests (0 = full blob)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveBlobRequest) Reset() {
	*x = RetrieveBlobRequest{}
	mi := &file_internal_cluster_proto_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveBlobRequest) ProtoMessage() {}

func (x *RetrieveBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveBlobRequest.ProtoReflect.Descriptor instead.
func (*RetrieveBlobRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_node_proto_rawDescGZIP(), []int{6}
}

func (x *RetrieveBlobRequest) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *RetrieveBlobRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RetrieveBlobRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

// RetrieveBlobResponse streams blob data back.
type RetrieveBlobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First message contains metadata, subsequent messages contain data chunks.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*RetrieveBlobResponse_Metadata
	//	*RetrieveBlobResponse_DataChunk
	Payload       isRetrieveBlobResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveBlobResponse) Reset() {
	*x = RetrieveBlobResponse{}
	mi := &file_internal_cluster_proto_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveBlobResponse) ProtoMessage() {}

func (x *RetrieveBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveBlobResponse.ProtoReflect.Descriptor instead.
func (*RetrieveBlobResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_node_proto_rawDescGZIP(), []int{7}
}

func (x *RetrieveBlobResponse) GetPayload() isRetrieveBlobResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RetrieveBlobResponse) GetMetadata() *BlobMetadata {
	if x != nil {
		if x, ok := x.Payload.(*RetrieveBlobResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *RetrieveBlobResponse) GetDataChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*RetrieveBlobResponse_DataChunk); ok {
			return x.DataChunk
		}
	}
	return nil
}

type isRetrieveBlobResponse_Payload interface {
	isRetrieveBlobResponse_Payload()
}

type RetrieveBlobResponse_Metadata struct {
	Metadata *BlobMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type RetrieveBlobResponse_DataChunk struct {
	DataChunk []byte `protobuf:"bytes,2,opt,name=data_chunk,json=dataChunk,proto3,oneof"`
}

func (*RetrieveBlobResponse_Metadata) isRetrieveBlobResponse_Payload() {}

func (*RetrieveBlobResponse_DataChunk) isRetrieveBlobResponse_Payload() {}

// DeleteBlobRequest requests deletion of a blob.
type DeleteBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentHash   string                 `protobuf:"bytes,1,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlobRequest) Reset() {
	*x = DeleteBlobRequest{}
	mi := &file_internal_cluster_proto_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlobRequest) ProtoMessage() {}

func (x *DeleteBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlobRequest.ProtoReflect.Descriptor instead.
func (*DeleteBlobRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_node_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteBlobRequest) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

// DeleteBlobResponse indicates the result of deletion.
type DeleteBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlobResponse) Reset() {
	*x = DeleteBlobResponse{}
	mi := &file_internal_cluster_proto_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlobResponse) ProtoMessage() {}

func (x *DeleteBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlobResponse.ProtoReflect.Descriptor instead.
func (*DeleteBlobResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_node_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteBlobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteBlobResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GetBlobMetadataRequest requests metadata for a blob.
type GetBlobMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentHash   string                 `protobuf:"bytes,1,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlobMetadataRequest) Reset() {
	*x = GetBlobMetadataRequest{}
	mi := &file_internal_cluster_proto_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlobMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobMetadataRequest) ProtoMessage() {}

func (x *GetBlobMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetBlobMetadataRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_node_proto_rawDescGZIP(), []int{10}
}

func (x *GetBlobMetadataRequest) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

// GetBlobMetadataResponse contains blob metadata.
type GetBlobMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Metadata      *BlobMetadata          `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlobMetadataResponse) Reset() {
	*x = GetBlobMetadataResponse{}
	mi := &file_internal_cluster_proto_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlobMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobMetadataResponse) ProtoMessage() {}

func (x *GetBlobMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetBlobMetadataResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_node_proto_rawDescGZIP(), []int{11}
}

func (x *GetBlobMetadataResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *GetBlobMetadataResponse) GetMetadata() *BlobMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ListBlobsRequest requests a list of blobs with optional filters.
type ListBlobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"` // Optional hash prefix filter
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`  // Max blobs to return
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"` // Pagination cursor
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlobsRequest) Reset() {
	*x = ListBlobsRequest{}
	mi := &file_internal_cluster_proto_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlobsRequest) ProtoMessage() {}

func (x *ListBlobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlobsRequest.ProtoReflect.Descriptor instead.
func (*ListBlobsRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_node_proto_rawDescGZIP(), []int{12}
}

func (x *ListBlobsRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListBlobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListBlobsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// ListBlobsResponse streams blob metadata.
type ListBlobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *BlobMetadata          `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // Empty if no more results
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlobsResponse) Reset() {
	*x = ListBlobsResponse{}
	mi := &file_internal_cluster_proto_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlobsResponse) ProtoMessage() {}

func (x *ListBlobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlobsResponse.ProtoReflect.Descriptor instead.
func (*ListBlobsResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_node_proto_rawDescGZIP(), []int{13}
}

func (x *ListBlobsResponse) GetMetadata() *BlobMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ListBlobsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

// RegisterNodeRequest registers a node with the cluster.
type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // host:port
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`       // "hot", "warm", "cold"
	StorageStats  *StorageStats          `protobuf:"bytes,4,opt,name=storage_stats,json=storageStats,proto3" json:"storage_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_internal_cluster_proto_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_node_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterNodeRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RegisterNodeRequest) GetStorageStats() *StorageStats {
	if x != nil {
		return x.StorageStats
	}
	return nil
}

// RegisterNodeResponse confirms registration.
type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ClusterNodes  []*NodeInfo            `protobuf:"bytes,3,rep,name=cluster_nodes,json=clusterNodes,proto3" json:"cluster_nodes,omitempty"` // Current cluster topology
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_internal_cluster_proto_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_node_proto_rawDescGZIP(), []int{15}
}

func (x *RegisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterNodeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RegisterNodeResponse) GetClusterNodes() []*NodeInfo {
	if x != nil {
		return x.ClusterNodes
	}
	return nil
}

// NodeInfo contains information about a cluster node.
type NodeInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address           string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Role              string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Status            string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	LastHeartbeatUnix int64                  `protobuf:"varint,5,opt,name=last_heartbeat_unix,json=lastHeartbeatUnix,proto3" json:"last_heartbeat_unix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_internal_cluster_proto_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_node_proto_rawDescGZIP(), []int{16}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *NodeInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeInfo) GetLastHeartbeatUnix() int64 {
	if x != nil {
		return x.LastHeartbeatUnix
	}
	return 0
}

// HeartbeatRequest sends periodic status update.
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	StorageStats  *StorageStats          `protobuf:"bytes,2,opt,name=storage_stats,json=storageStats,proto3" json:"storage_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_internal_cluster_proto_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_node_proto_rawDescGZIP(), []int{17}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetStorageStats() *StorageStats {
	if x != nil {
		return x.StorageStats
	}
	return nil
}

// HeartbeatResponse acknowledges heartbeat.
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UpdatedNodes  []*NodeInfo            `protobuf:"bytes,2,rep,name=updated_nodes,json=updatedNodes,proto3" json:"updated_nodes,omitempty"` // Nodes with changed status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_internal_cluster_proto_node_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_node_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_node_proto_rawDescGZIP(), []int{18}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetUpdatedNodes() []*NodeInfo {
	if x != nil {
		return x.UpdatedNodes
	}
	return nil
}

var File_internal_cluster_proto_node_proto protoreflect.FileDescriptor

const file_internal_cluster_proto_node_proto_rawDesc = "" +
	"\n" +
	"!internal/cluster/proto/node.proto\x12\acluster\"\r\n" +
	"\vPingRequest\"\xb6\x01\n" +
	"\fPingResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\x12:\n" +
	"\rstorage_stats\x18\x05 \x01(\v2\x15.cluster.StorageStatsR\fstorageStats\"\x8c\x01\n" +
	"\fStorageStats\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\x03R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x02 \x01(\x03R\tusedBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x03 \x01(\x03R\tfreeBytes\x12\x1d\n" +
	"\n" +
	"blob_count\x18\x04 \x01(\x03R\tblobCount\"v\n" +
	"\x13TransferBlobRequest\x123\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.cluster.BlobMetadataH\x00R\bmetadata\x12\x1f\n" +
	"\n" +
	"data_chunk\x18\x02 \x01(\fH\x00R\tdataChunkB\t\n" +
	"\apayload\"\xd7\x01\n" +
	"\fBlobMetadata\x12!\n" +
	"\fcontent_hash\x18\x01 \x01(\tR\vcontentHash\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12!\n" +
	"\fis_encrypted\x18\x03 \x01(\bR\visEncrypted\x12+\n" +
	"\x11encryption_scheme\x18\x04 \x01(\tR\x10encryptionScheme\x12#\n" +
	"\rencryption_iv\x18\x05 \x01(\tR\fencryptionIv\x12\x1b\n" +
	"\tblob_type\x18\x06 \x01(\tR\bblobType\"x\n" +
	"\x14TransferBlobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12!\n" +
	"\fcontent_hash\x18\x03 \x01(\tR\vcontentHash\"h\n" +
	"\x13RetrieveBlobRequest\x12!\n" +
	"\fcontent_hash\x18\x01 \x01(\tR\vcontentHash\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\"w\n" +
	"\x14RetrieveBlobResponse\x123\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.cluster.BlobMetadataH\x00R\bmetadata\x12\x1f\n" +
	"\n" +
	"data_chunk\x18\x02 \x01(\fH\x00R\tdataChunkB\t\n" +
	"\apayload\"6\n" +
	"\x11DeleteBlobRequest\x12!\n" +
	"\fcontent_hash\x18\x01 \x01(\tR\vcontentHash\"S\n" +
	"\x12DeleteBlobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\";\n" +
	"\x16GetBlobMetadataRequest\x12!\n" +
	"\fcontent_hash\x18\x01 \x01(\tR\vcontentHash\"d\n" +
	"\x17GetBlobMetadataResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x121\n" +
	"\bmetadata\x18\x02 \x01(\v2\x15.cluster.BlobMetadataR\bmetadata\"X\n" +
	"\x10ListBlobsRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"g\n" +
	"\x11ListBlobsResponse\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.cluster.BlobMetadataR\bmetadata\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\x98\x01\n" +
	"\x13RegisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12:\n" +
	"\rstorage_stats\x18\x04 \x01(\v2\x15.cluster.StorageStatsR\fstorageStats\"\x8d\x01\n" +
	"\x14RegisterNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x126\n" +
	"\rcluster_nodes\x18\x03 \x03(\v2\x11.cluster.NodeInfoR\fclusterNodes\"\x99\x01\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12.\n" +
	"\x13last_heartbeat_unix\x18\x05 \x01(\x03R\x11lastHeartbeatUnix\"g\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12:\n" +
	"\rstorage_stats\x18\x02 \x01(\v2\x15.cluster.StorageStatsR\fstorageStats\"e\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x126\n" +
	"\rupdated_nodes\x18\x02 \x03(\v2\x11.cluster.NodeInfoR\fupdatedNodes2\xd4\x04\n" +
	"\vNodeService\x123\n" +
	"\x04Ping\x12\x14.cluster.PingRequest\x1a\x15.cluster.PingResponse\x12M\n" +
	"\fTransferBlob\x12\x1c.cluster.TransferBlobRequest\x1a\x1d.cluster.TransferBlobResponse(\x01\x12M\n" +
	"\fRetrieveBlob\x12\x1c.cluster.RetrieveBlobRequest\x1a\x1d.cluster.RetrieveBlobResponse0\x01\x12E\n" +
	"\n" +
	"DeleteBlob\x12\x1a.cluster.DeleteBlobRequest\x1a\x1b.cluster.DeleteBlobResponse\x12T\n" +
	"\x0fGetBlobMetadata\x12\x1f.cluster.GetBlobMetadataRequest\x1a .cluster.GetBlobMetadataResponse\x12D\n" +
	"\tListBlobs\x12\x19.cluster.ListBlobsRequest\x1a\x1a.cluster.ListBlobsResponse0\x01\x12K\n" +
	"\fRegisterNode\x12\x1c.cluster.RegisterNodeRequest\x1a\x1d.cluster.RegisterNodeResponse\x12B\n" +
	"\tHeartbeat\x12\x19.cluster.HeartbeatRequest\x1a\x1a.cluster.HeartbeatResponseB<Z:github.com/prn-tf/alexander-storage/internal/cluster/protob\x06proto3"

var (
	file_internal_cluster_proto_node_proto_rawDescOnce sync.Once
	file_internal_cluster_proto_node_proto_rawDescData []byte
)

func file_internal_cluster_proto_node_proto_rawDescGZIP() []byte {
	file_internal_cluster_proto_node_proto_rawDescOnce.Do(func() {
		file_internal_cluster_proto_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_cluster_proto_node_proto_rawDesc), len(file_internal_cluster_proto_node_proto_rawDesc)))
	})
	return file_internal_cluster_proto_node_proto_rawDescData
}

var file_internal_cluster_proto_node_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_internal_cluster_proto_node_proto_goTypes = []any{
	(*PingRequest)(nil),             // 0: cluster.PingRequest
	(*PingResponse)(nil),            // 1: cluster.PingResponse
	(*StorageStats)(nil),            // 2: cluster.StorageStats
	(*TransferBlobRequest)(nil),     // 3: cluster.TransferBlobRequest
	(*BlobMetadata)(nil),            // 4: cluster.BlobMetadata
	(*TransferBlobResponse)(nil),    // 5: cluster.TransferBlobResponse
	(*RetrieveBlobRequest)(nil),     // 6: cluster.RetrieveBlobRequest
	(*RetrieveBlobResponse)(nil),    // 7: cluster.RetrieveBlobResponse
	(*DeleteBlobRequest)(nil),       // 8: cluster.DeleteBlobRequest
	(*DeleteBlobResponse)(nil),      // 9: cluster.DeleteBlobResponse
	(*GetBlobMetadataRequest)(nil),  // 10: cluster.GetBlobMetadataRequest
	(*GetBlobMetadataResponse)(nil), // 11: cluster.GetBlobMetadataResponse
	(*ListBlobsRequest)(nil),        // 12: cluster.ListBlobsRequest
	(*ListBlobsResponse)(nil),       // 13: cluster.ListBlobsResponse
	(*RegisterNodeRequest)(nil),     // 14: cluster.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),    // 15: cluster.RegisterNodeResponse
	(*NodeInfo)(nil),                // 16: cluster.NodeInfo
	(*HeartbeatRequest)(nil),        // 17: cluster.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 18: cluster.HeartbeatResponse
}
var file_internal_cluster_proto_node_proto_depIdxs = []int32{
	2,  // 0: cluster.PingResponse.storage_stats:type_name -> cluster.StorageStats
	4,  // 1: cluster.TransferBlobRequest.metadata:type_name -> cluster.BlobMetadata
	4,  // 2: cluster.RetrieveBlobResponse.metadata:type_name -> cluster.BlobMetadata
	4,  // 3: cluster.GetBlobMetadataResponse.metadata:type_name -> cluster.BlobMetadata
	4,  // 4: cluster.ListBlobsResponse.metadata:type_name -> cluster.BlobMetadata
	2,  // 5: cluster.RegisterNodeRequest.storage_stats:type_name -> cluster.StorageStats
	16, // 6: cluster.RegisterNodeResponse.cluster_nodes:type_name -> cluster.NodeInfo
	2,  // 7: cluster.HeartbeatRequest.storage_stats:type_name -> cluster.StorageStats
	16, // 8: cluster.HeartbeatResponse.updated_nodes:type_name -> cluster.NodeInfo
	0,  // 9: cluster.NodeService.Ping:input_type -> cluster.PingRequest
	3,  // 10: cluster.NodeService.TransferBlob:input_type -> cluster.TransferBlobRequest
	6,  // 11: cluster.NodeService.RetrieveBlob:input_type -> cluster.RetrieveBlobRequest
	8,  // 12: cluster.NodeService.DeleteBlob:input_type -> cluster.DeleteBlobRequest
	10, // 13: cluster.NodeService.GetBlobMetadata:input_type -> cluster.GetBlobMetadataRequest
	12, // 14: cluster.NodeService.ListBlobs:input_type -> cluster.ListBlobsRequest
	14, // 15: cluster.NodeService.RegisterNode:input_type -> cluster.RegisterNodeRequest
	17, // 16: cluster.NodeService.Heartbeat:input_type -> cluster.HeartbeatRequest
	1,  // 17: cluster.NodeService.Ping:output_type -> cluster.PingResponse
	5,  // 18: cluster.NodeService.TransferBlob:output_type -> cluster.TransferBlobResponse
	7,  // 19: cluster.NodeService.RetrieveBlob:output_type -> cluster.RetrieveBlobResponse
	9,  // 20: cluster.NodeService.DeleteBlob:output_type -> cluster.DeleteBlobResponse
	11, // 21: cluster.NodeService.GetBlobMetadata:output_type -> cluster.GetBlobMetadataResponse
	13, // 22: cluster.NodeService.ListBlobs:output_type -> cluster.ListBlobsResponse
	15, // 23: cluster.NodeService.RegisterNode:output_type -> cluster.RegisterNodeResponse
	18, // 24: cluster.NodeService.Heartbeat:output_type -> cluster.HeartbeatResponse
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_internal_cluster_proto_node_proto_init() }
func file_internal_cluster_proto_node_proto_init() {
	if File_internal_cluster_proto_node_proto != nil {
		return
	}
	file_internal_cluster_proto_node_proto_msgTypes[3].OneofWrappers = []any{
		(*TransferBlobRequest_Metadata)(nil),
		(*TransferBlobRequest_DataChunk)(nil),
	}
	file_internal_cluster_proto_node_proto_msgTypes[7].OneofWrappers = []any{
		(*RetrieveBlobResponse_Metadata)(nil),
		(*RetrieveBlobResponse_DataChunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_cluster_proto_node_proto_rawDesc), len(file_internal_cluster_proto_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_cluster_proto_node_proto_goTypes,
		DependencyIndexes: file_internal_cluster_proto_node_proto_depIdxs,
		MessageInfos:      file_internal_cluster_proto_node_proto_msgTypes,
	}.Build()
	File_internal_cluster_proto_node_proto = out.File
	file_internal_cluster_proto_node_proto_goTypes = nil
	file_internal_cluster_proto_node_proto_depIdxs = nil
}
