// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: internal/cluster/proto/node.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_Ping_FullMethodName            = "/cluster.NodeService/Ping"
	NodeService_TransferBlob_FullMethodName    = "/cluster.NodeService/TransferBlob"
	NodeService_RetrieveBlob_FullMethodName    = "/cluster.NodeService/RetrieveBlob"
	NodeService_DeleteBlob_FullMethodName      = "/cluster.NodeService/DeleteBlob"
	NodeService_GetBlobMetadata_FullMethodName = "/cluster.NodeService/GetBlobMetadata"
	NodeService_ListBlobs_FullMethodName       = "/cluster.NodeService/ListBlobs"
	NodeService_RegisterNode_FullMethodName    = "/cluster.NodeService/RegisterNode"
	NodeService_Heartbeat_FullMethodName       = "/cluster.NodeService/Heartbeat"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeService provides gRPC methods for inter-node communication.
type NodeServiceClient interface {
	// Ping checks if a node is alive and returns its status.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// TransferBlob transfers a blob from one node to another.
	TransferBlob(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TransferBlobRequest, TransferBlobResponse], error)
	// RetrieveBlob retrieves a blob from a remote node.
	RetrieveBlob(ctx context.Context, in *RetrieveBlobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RetrieveBlobResponse], error)
	// DeleteBlob deletes a blob from a node.
	DeleteBlob(ctx context.Context, in *DeleteBlobRequest, opts ...grpc.CallOption) (*DeleteBlobResponse, error)
	// GetBlobMetadata gets metadata about a blob on a node.
	GetBlobMetadata(ctx context.Context, in *GetBlobMetadataRequest, opts ...grpc.CallOption) (*GetBlobMetadataResponse, error)
	// ListBlobs lists all blobs on a node with optional filtering.
	ListBlobs(ctx context.Context, in *ListBlobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListBlobsResponse], error)
	// RegisterNode registers this node with the cluster coordinator.
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	// Heartbeat sends periodic heartbeat to cluster coordinator.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, NodeService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) TransferBlob(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TransferBlobRequest, TransferBlobResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[0], NodeService_TransferBlob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TransferBlobRequest, TransferBlobResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_TransferBlobClient = grpc.ClientStreamingClient[TransferBlobRequest, TransferBlobResponse]

func (c *nodeServiceClient) RetrieveBlob(ctx context.Context, in *RetrieveBlobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RetrieveBlobResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[1], NodeService_RetrieveBlob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RetrieveBlobRequest, RetrieveBlobResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_RetrieveBlobClient = grpc.ServerStreamingClient[RetrieveBlobResponse]

func (c *nodeServiceClient) DeleteBlob(ctx context.Context, in *DeleteBlobRequest, opts ...grpc.CallOption) (*DeleteBlobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBlobResponse)
	err := c.cc.Invoke(ctx, NodeService_DeleteBlob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetBlobMetadata(ctx context.Context, in *GetBlobMetadataRequest, opts ...grpc.CallOption) (*GetBlobMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlobMetadataResponse)
	err := c.cc.Invoke(ctx, NodeService_GetBlobMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ListBlobs(ctx context.Context, in *ListBlobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListBlobsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[2], NodeService_ListBlobs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListBlobsRequest, ListBlobsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_ListBlobsClient = grpc.ServerStreamingClient[ListBlobsResponse]

func (c *nodeServiceClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, NodeService_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, NodeService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
//
// NodeService provides gRPC methods for inter-node communication.
type NodeServiceServer interface {
	// Ping checks if a node is alive and returns its status.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// TransferBlob transfers a blob from one node to another.
	TransferBlob(grpc.ClientStreamingServer[TransferBlobRequest, TransferBlobResponse]) error
	// RetrieveBlob retrieves a blob from a remote node.
	RetrieveBlob(*RetrieveBlobRequest, grpc.ServerStreamingServer[RetrieveBlobResponse]) error
	// DeleteBlob deletes a blob from a node.
	DeleteBlob(context.Context, *DeleteBlobRequest) (*DeleteBlobResponse, error)
	// GetBlobMetadata gets metadata about a blob on a node.
	GetBlobMetadata(context.Context, *GetBlobMetadataRequest) (*GetBlobMetadataResponse, error)
	// ListBlobs lists all blobs on a node with optional filtering.
	ListBlobs(*ListBlobsRequest, grpc.ServerStreamingServer[ListBlobsResponse]) error
	// RegisterNode registers this node with the cluster coordinator.
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	// Heartbeat sends periodic heartbeat to cluster coordinator.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedNodeServiceServer) TransferBlob(grpc.ClientStreamingServer[TransferBlobRequest, TransferBlobResponse]) error {
	return status.Error(codes.Unimplemented, "method TransferBlob not implemented")
}
func (UnimplementedNodeServiceServer) RetrieveBlob(*RetrieveBlobRequest, grpc.ServerStreamingServer[RetrieveBlobResponse]) error {
	return status.Error(codes.Unimplemented, "method RetrieveBlob not implemented")
}
func (UnimplementedNodeServiceServer) DeleteBlob(context.Context, *DeleteBlobRequest) (*DeleteBlobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBlob not implemented")
}
func (UnimplementedNodeServiceServer) GetBlobMetadata(context.Context, *GetBlobMetadataRequest) (*GetBlobMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlobMetadata not implemented")
}
func (UnimplementedNodeServiceServer) ListBlobs(*ListBlobsRequest, grpc.ServerStreamingServer[ListBlobsResponse]) error {
	return status.Error(codes.Unimplemented, "method ListBlobs not implemented")
}
func (UnimplementedNodeServiceServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedNodeServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_TransferBlob_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServiceServer).TransferBlob(&grpc.GenericServerStream[TransferBlobRequest, TransferBlobResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_TransferBlobServer = grpc.ClientStreamingServer[TransferBlobRequest, TransferBlobResponse]

func _NodeService_RetrieveBlob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RetrieveBlobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).RetrieveBlob(m, &grpc.GenericServerStream[RetrieveBlobRequest, RetrieveBlobResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_RetrieveBlobServer = grpc.ServerStreamingServer[RetrieveBlobResponse]

func _NodeService_DeleteBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).DeleteBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_DeleteBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).DeleteBlob(ctx, req.(*DeleteBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetBlobMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlobMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetBlobMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetBlobMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetBlobMetadata(ctx, req.(*GetBlobMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ListBlobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListBlobsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).ListBlobs(m, &grpc.GenericServerStream[ListBlobsRequest, ListBlobsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_ListBlobsServer = grpc.ServerStreamingServer[ListBlobsResponse]

func _NodeService_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cluster.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _NodeService_Ping_Handler,
		},
		{
			MethodName: "DeleteBlob",
			Handler:    _NodeService_DeleteBlob_Handler,
		},
		{
			MethodName: "GetBlobMetadata",
			Handler:    _NodeService_GetBlobMetadata_Handler,
		},
		{
			MethodName: "RegisterNode",
			Handler:    _NodeService_RegisterNode_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _NodeService_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransferBlob",
			Handler:       _NodeService_TransferBlob_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "RetrieveBlob",
			Handler:       _NodeService_RetrieveBlob_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListBlobs",
			Handler:       _NodeService_ListBlobs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/cluster/proto/node.proto",
}
