#!/bin/bash
#
# Alexander S3 Storage - Linux/macOS Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/neuralforgeone/alexander-storage/main/scripts/install.sh | bash
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
INSTALL_DIR="${INSTALL_DIR:-/usr/local/bin}"
CONFIG_DIR="${CONFIG_DIR:-/etc/alexander}"
DATA_DIR="${DATA_DIR:-/var/lib/alexander}"
REPO="neuralforgeone/alexander-storage"
SERVICE_USER="alexander"

# Functions
print_banner() {
    echo -e "${BLUE}"
    echo "╔═══════════════════════════════════════════════════════════╗"
    echo "║           Alexander S3 Storage Installer                  ║"
    echo "║               S3-Compatible Object Storage                ║"
    echo "╚═══════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

detect_os() {
    OS="$(uname -s)"
    ARCH="$(uname -m)"
    
    case "$OS" in
        Linux*)     OS_TYPE="linux";;
        Darwin*)    OS_TYPE="darwin";;
        *)          log_error "Unsupported OS: $OS"; exit 1;;
    esac
    
    case "$ARCH" in
        x86_64)     ARCH_TYPE="amd64";;
        amd64)      ARCH_TYPE="amd64";;
        aarch64)    ARCH_TYPE="arm64";;
        arm64)      ARCH_TYPE="arm64";;
        *)          log_error "Unsupported architecture: $ARCH"; exit 1;;
    esac
    
    log_info "Detected: $OS_TYPE-$ARCH_TYPE"
}

get_latest_version() {
    log_info "Fetching latest version..."
    VERSION=$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" | grep '"tag_name"' | sed -E 's/.*"v([^"]+)".*/\1/')
    
    if [[ -z "$VERSION" ]]; then
        log_error "Could not determine latest version"
        exit 1
    fi
    
    log_info "Latest version: v$VERSION"
}

download_binaries() {
    DOWNLOAD_URL="https://github.com/${REPO}/releases/download/v${VERSION}/alexander-${VERSION}-${OS_TYPE}-${ARCH_TYPE}.tar.gz"
    
    log_info "Downloading from: $DOWNLOAD_URL"
    
    TMP_DIR=$(mktemp -d)
    cd "$TMP_DIR"
    
    curl -fsSL "$DOWNLOAD_URL" -o alexander.tar.gz
    tar -xzf alexander.tar.gz
    
    log_info "Installing binaries to $INSTALL_DIR"
    mv alexander-server-${OS_TYPE}-${ARCH_TYPE} "$INSTALL_DIR/alexander-server"
    mv alexander-admin-${OS_TYPE}-${ARCH_TYPE} "$INSTALL_DIR/alexander-admin"
    mv alexander-migrate-${OS_TYPE}-${ARCH_TYPE} "$INSTALL_DIR/alexander-migrate"
    
    chmod +x "$INSTALL_DIR/alexander-server"
    chmod +x "$INSTALL_DIR/alexander-admin"
    chmod +x "$INSTALL_DIR/alexander-migrate"
    
    cd /
    rm -rf "$TMP_DIR"
}

create_user() {
    if id "$SERVICE_USER" &>/dev/null; then
        log_info "User $SERVICE_USER already exists"
    else
        log_info "Creating service user: $SERVICE_USER"
        useradd -r -s /bin/false "$SERVICE_USER"
    fi
}

create_directories() {
    log_info "Creating directories..."
    
    mkdir -p "$CONFIG_DIR"
    mkdir -p "$DATA_DIR/data"
    mkdir -p "$DATA_DIR/blobs"
    
    chown -R "$SERVICE_USER:$SERVICE_USER" "$DATA_DIR"
    chmod 750 "$DATA_DIR"
}

generate_master_key() {
    MASTER_KEY=$(openssl rand -hex 32)
    SSE_KEY=$(openssl rand -hex 32)
    echo "$MASTER_KEY" > "$CONFIG_DIR/.master_key"
    echo "$SSE_KEY" > "$CONFIG_DIR/.sse_key"
    chmod 600 "$CONFIG_DIR/.master_key" "$CONFIG_DIR/.sse_key"
    chown root:root "$CONFIG_DIR/.master_key" "$CONFIG_DIR/.sse_key"
    log_info "Generated master keys (saved to $CONFIG_DIR/)"
}

create_config() {
    if [[ -f "$CONFIG_DIR/config.yaml" ]]; then
        log_warn "Config file already exists, skipping..."
        return
    fi
    
    MASTER_KEY=$(cat "$CONFIG_DIR/.master_key")
    SSE_KEY=$(cat "$CONFIG_DIR/.sse_key")
    
    log_info "Creating configuration file..."
    
    cat > "$CONFIG_DIR/config.yaml" << EOF
# Alexander S3 Storage Configuration
# Generated by installer on $(date)

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 60s
  shutdown_timeout: 30s

database:
  # Use "sqlite" for single-node or "postgres" for production
  driver: "sqlite"
  
  # SQLite settings (when driver: sqlite)
  path: "${DATA_DIR}/data/alexander.db"
  journal_mode: "WAL"
  busy_timeout: 5000
  cache_size: -2000
  synchronous_mode: "NORMAL"
  
  # PostgreSQL settings (when driver: postgres)
  # host: "localhost"
  # port: 5432
  # name: "alexander"
  # user: "alexander"
  # password: "your_password"
  # ssl_mode: "disable"
  # max_open_conns: 25
  # max_idle_conns: 5

storage:
  backend: "filesystem"
  filesystem:
    base_path: "${DATA_DIR}/blobs"

auth:
  master_key: "${MASTER_KEY}"
  sse_master_key: "${SSE_KEY}"

redis:
  # Set to true for distributed deployments
  enabled: false
  host: "localhost"
  port: 6379
  password: ""
  db: 0

metrics:
  enabled: true
  port: 9091
  path: "/metrics"

rate_limit:
  enabled: true
  requests_per_second: 100
  burst_size: 200

gc:
  enabled: true
  interval: "1h"
  grace_period: "24h"
  batch_size: 1000

logging:
  level: "info"
  format: "json"
EOF
    
    chmod 640 "$CONFIG_DIR/config.yaml"
    chown root:"$SERVICE_USER" "$CONFIG_DIR/config.yaml"
}

install_systemd_service() {
    if [[ "$OS_TYPE" != "linux" ]]; then
        log_warn "Systemd service only available on Linux"
        return
    fi
    
    log_info "Installing systemd service..."
    
    cat > /etc/systemd/system/alexander.service << EOF
[Unit]
Description=Alexander S3 Storage Server
Documentation=https://github.com/${REPO}
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_USER}
ExecStart=${INSTALL_DIR}/alexander-server --config ${CONFIG_DIR}/config.yaml
ExecReload=/bin/kill -HUP \$MAINPID
Restart=always
RestartSec=5
TimeoutStopSec=30

# Security hardening
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
ReadWritePaths=${DATA_DIR}
PrivateTmp=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes

# Resource limits
LimitNOFILE=65535
LimitNPROC=4096

[Install]
WantedBy=multi-user.target
EOF
    
    systemctl daemon-reload
    log_info "Systemd service installed"
}

install_launchd_service() {
    if [[ "$OS_TYPE" != "darwin" ]]; then
        return
    fi
    
    log_info "Installing launchd service..."
    
    cat > /Library/LaunchDaemons/com.alexander.server.plist << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.alexander.server</string>
    <key>ProgramArguments</key>
    <array>
        <string>${INSTALL_DIR}/alexander-server</string>
        <string>--config</string>
        <string>${CONFIG_DIR}/config.yaml</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/var/log/alexander.log</string>
    <key>StandardErrorPath</key>
    <string>/var/log/alexander.error.log</string>
</dict>
</plist>
EOF
    
    log_info "LaunchDaemon installed"
}

create_admin_user() {
    log_info "Creating initial admin user..."
    
    ADMIN_PASS=$(openssl rand -base64 12)
    
    "$INSTALL_DIR/alexander-admin" user create \
        --config "$CONFIG_DIR/config.yaml" \
        --username admin \
        --email "admin@localhost" \
        --password "$ADMIN_PASS" \
        --admin 2>/dev/null || true
    
    echo ""
    echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}  Admin User Created${NC}"
    echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
    echo -e "  Username: ${YELLOW}admin${NC}"
    echo -e "  Password: ${YELLOW}${ADMIN_PASS}${NC}"
    echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
    echo ""
    echo -e "${RED}  ⚠️  Save this password! It won't be shown again.${NC}"
    echo ""
}

create_access_key() {
    log_info "Creating initial access key..."
    
    OUTPUT=$("$INSTALL_DIR/alexander-admin" accesskey create \
        --config "$CONFIG_DIR/config.yaml" \
        --user-id 1 \
        --json 2>/dev/null) || true
    
    if [[ -n "$OUTPUT" ]]; then
        ACCESS_KEY=$(echo "$OUTPUT" | grep -o '"access_key_id":"[^"]*"' | cut -d'"' -f4)
        SECRET_KEY=$(echo "$OUTPUT" | grep -o '"secret_access_key":"[^"]*"' | cut -d'"' -f4)
        
        echo ""
        echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
        echo -e "${GREEN}  S3 Access Keys Created${NC}"
        echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
        echo -e "  Access Key ID:     ${YELLOW}${ACCESS_KEY}${NC}"
        echo -e "  Secret Access Key: ${YELLOW}${SECRET_KEY}${NC}"
        echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
        echo ""
        echo -e "${RED}  ⚠️  Save these keys! They won't be shown again.${NC}"
        echo ""
    fi
}

print_completion() {
    echo ""
    echo -e "${GREEN}╔═══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║           Installation Complete! 🎉                       ║${NC}"
    echo -e "${GREEN}╚═══════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "  Binaries installed to: $INSTALL_DIR"
    echo "  Configuration: $CONFIG_DIR/config.yaml"
    echo "  Data directory: $DATA_DIR"
    echo ""
    
    if [[ "$OS_TYPE" == "linux" ]]; then
        echo "  Start the service:"
        echo -e "    ${BLUE}sudo systemctl start alexander${NC}"
        echo -e "    ${BLUE}sudo systemctl enable alexander${NC}"
        echo ""
        echo "  Check status:"
        echo -e "    ${BLUE}sudo systemctl status alexander${NC}"
    elif [[ "$OS_TYPE" == "darwin" ]]; then
        echo "  Start the service:"
        echo -e "    ${BLUE}sudo launchctl load /Library/LaunchDaemons/com.alexander.server.plist${NC}"
    fi
    
    echo ""
    echo "  Test with AWS CLI:"
    echo -e "    ${BLUE}aws --endpoint-url http://localhost:8080 s3 ls${NC}"
    echo ""
    echo "  Dashboard:"
    echo -e "    ${BLUE}http://localhost:8080/dashboard${NC}"
    echo ""
    echo "  Documentation:"
    echo -e "    ${BLUE}https://github.com/${REPO}${NC}"
    echo ""
}

# Main
main() {
    print_banner
    check_root
    detect_os
    get_latest_version
    download_binaries
    create_user
    create_directories
    generate_master_key
    create_config
    
    if [[ "$OS_TYPE" == "linux" ]]; then
        install_systemd_service
    elif [[ "$OS_TYPE" == "darwin" ]]; then
        install_launchd_service
    fi
    
    create_admin_user
    create_access_key
    print_completion
}

main "$@"
